[env:esp01]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 9600
upload_speed = 115200

lib_deps =
    tzapu/WiFiManager @ ^2.0.17

build_flags =
    -DCORE_DEBUG_LEVEL=0
